AB#142
UKGovernmentBEIS/transparency-db-admin-portal pull request #262
Opened 2022-10-03 10:33 UTC by bill-batten

- Scheme to include confirmation date.
- Added all of the necessary validation as well as a refactoring some large if statements which retrieved the month name from an int value

2022-10-05 08:52 UTC, holderj requested changes

2022-10-06 15:36 UTC, bill-batten commented on routes/subsidymeasure-edit.js
> +        // var date = Scheme_Start_Date.split(" ");
Comment addressed

2022-10-06 15:37 UTC, bill-batten commented on views/bulkupload/addsubsidyaward.ejs
> +                <% if( ssn.Subsidy_Objective_Global == 'Rescue subsidy' ){ %>
I have left this for now and will resolve merge conflicts that arise as there are lots of changes needed.

2022-11-23 07:38 UTC, holderj approved these changes

2022-11-23 07:40 UTC, merged